### ISSUE TITLE
Error after installation: Auth driver [jwt] for guard [api] is not defined.

### ISSUE THREAD

**Issue by mfn** [fntneves/laravel-transactional-events#26]
Package version: 1.8.2
Laravel version: 5.8.32

Installation is performed but as soon as any framework code is executed (`./artisan` is enough), it 'splodes:
```
./composer.phar require fntneves/laravel-transactional-events
Using version ^1.8 for fntneves/laravel-transactional-events
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing drupol/phptree (2.4.4): Loading from cache
  - Installing fntneves/laravel-transactional-events (1.8.2): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In AuthManager.php line 97:

  Auth driver [jwt] for guard [api] is not defined.


PHP Fatal error:  Uncaught InvalidArgumentException: Auth driver [jwt] for guard [api] is not defined. in /vagrant/project/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:97
Stack trace:
#0 /vagrant/project/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\Auth\AuthManager->resolve('api')
#1 /vagrant/project/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(297): Illuminate\Auth\AuthManager->guard()
#2 /vagrant/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\Auth\AuthManager->__call('check', Array)
#3 /vagrant/project/app/Services/Sentry.php(36): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#4 /vagrant/project/vendor/sentry/sentry/src/State/Hub.php(106): App\Services\Sentry->App\Services\{closure}(Object(Sentry\State\Scope))
#5 /vagrant/project/app/Services/Sentry.php(41): Sentry\State\Hub->configureScope(Object(Closure))
#6 /vagrant/project/app/Exceptions/Handler.php in /vagrant/project/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 97

In AuthManager.php line 97:

  Auth driver [jwt] for guard [api] is not defined.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```
I can work around the installation problem by disabling auto-discovery in the `composer.json`:
```json
  "extra": {
    "laravel": {
      "dont-discover": [
        "fntneves/laravel-transactional-events"
      ]
    }
```
But as son as I add `\Neves\Events\EventServiceProvider` to `config/app` into `providers` I'm were I started.

I'm also using https://github.com/tymondesigns/jwt-auth .

When I debug the above exception I end up in `\Illuminate\Auth\AuthManager::resolve` where said exception is thrown.

The last thing it tried was to look for a method called `createJwtDriver`:
```php
…
        $driverMethod = 'create'.ucfirst($config['driver']).'Driver';

        if (method_exists($this, $driverMethod)) {
            return $this->{$driverMethod}($name, $config);
        }

        throw new InvalidArgumentException(
            "Auth driver [{$config['driver']}] for guard [{$name}] is not defined."
        );
```
It's somehow connected to this code in `\Illuminate\Auth\AuthServiceProvider::registerEventRebindHandler`:
```php
        $this->app->rebinding('events', function ($app, $dispatcher) {
            if (! $app->resolved('auth')) {
                return;
            }

            if (method_exists($guard = $app['auth']->guard(), 'setDispatcher')) {
                $guard->setDispatcher($dispatcher);
            }
        });
```
It talks about event and rebinding… 🤷‍♀️

The JWT serviceprovider has this:
```php
    /**
     * Extend Laravel's Auth.
     *
     * @return void
     */
    protected function extendAuthGuard()
    {
        $this->app['auth']->extend('jwt', function ($app, $name, array $config) {
            $guard = new JWTGuard(
                $app['tymon.jwt'],
                $app['auth']->createUserProvider($config['provider']),
                $app['request']
            );

            $app->refresh('request', $guard, 'setRequest');

            return $guard;
        });
    }
```
This "extend" should not require the `createJwtDriver` to be called etc. but it seems maybe this is triggered _before_ the JWT driver is fully initialized; hard to say.

I also tried moving this package ServiceProvider before the JWT but no avail.

I temporarily tried to disable the `'api'` auth driver (requiring jwt) but the fun thing is that other `'web'` driver is **also** custom and I suffer the same problem.

It seems the auth guard is requested in a scope when the auth stuff is not fully booted?

When I go to `\Illuminate\Auth\AuthServiceProvider::register` and comment out this line, at least artisan does not crash anymore:
```php
    public function register()
    {
        $this->registerAuthenticator();
        $this->registerUserResolver();
        $this->registerAccessGate();
        $this->registerRequestRebindHandler();
//        $this->registerEventRebindHandler();
    }
```
Not sure if it makes sense to try to proceed with this package at this point though.

Any idea? 😄

**Comment by mfn** [comment]
Found the problem: I had a custom "user" provider registered in `App\Providers\AuthServiceProvider::register()`, like this:
```php
        $this->app->make('auth')->provider('…', function (Application $app, array $config) {
            return new …;
        });
```
The problem: `register()` is only for registering, not running code (i.e. `make('auth')->provider(…)`).

Moving it up to `App\Providers\AuthServiceProvider::boot` fixed it.

Had this code erroneously for years this way and this was the first package triggering it 🤷‍♀️

Sorry for the noise!
